### PR TITLE
Start restructuring of Attribute subtree

### PR DESCRIPTION
**Pull request by VisLab**
This pull request moves many of the temporal and spatial attributes under Attribute/Temporal and Attribute/Spatial respectively.  It partially addressed issue #39.

I am making this pull request so that we can generate XML and test that the validators don't break under these changes.

### CODE REVIEW

**Comment by happy5214** [comment]
I see that we have Attribute/Temporal/Temporal rate and Attribute/Temporal/Temporal uncertainty. Do we need both Temporal uses in those tags, or can we simplify them to Attribute/Temporal/Rate and Attribute/Temporal/Uncertainty?

**Comment by VisLab** [comment]
Agreed.... will change

**Comment by happy5214** [comment]
It doesn't appear the changes I suggested were made.

**Comment by happy5214** [comment]
I see that the changes were made in #49.

**Pull request merged**
