### PR TITLE
Add a test for Volt vs volt

### PR DESCRIPTION
**Pull request by IanCa**

### CODE REVIEW

**Comment by VisLab** [comment]
Let's hold off on this until it is discussed at the HWG.  We may want to support both Volt and volt?

**Comment by IanCa** [comment]
To clarify, both work, and that’s what it tests.Case only matters on unit symbols Sent from my iPhoneOn Mar 11, 2024, at 9:09 AM, Kay Robbins ***@***.***> wrote:﻿
Let's hold off on this until it is discussed at the HWG.  We may want to support both Volt and volt?

**Comment by happy5214** [comment]
However, this is a schema test that's supposed to fail, so I'm assuming it's testing that you can't put both forms in the schema (which would be redundant)?

**Comment by IanCa** [comment]
Yeah, it should be a duplicate node error if a non symbol is present twice with mixed case.(Volt vs volt)

but Unit symbol V vs v would be allowed(the second test)

**Comment by VisLab** [comment]
You are right.... case doesn't matter in general.  I think we need to
clarify case sensitivity in the specification.  Case doesn't matter in the
tags.  It does matter in unit modifiers and unit symbols. It probably
shouldn't matter in schema attributes and properties or should it?

**Comment by IanCa** [comment]
I haven't implemented case not mattering beyond tags and units/unit modifiers, but I don't see any reason unit classes, value classes, attributes, or properties need case sensitivity.

**Comment by happy5214** [comment]
> It does matter in unit modifiers and unit symbols.

This is not entirely true. Case only matters for unit modifiers if they have the `SIUnitSymbolModifier` attribute.

I think there's a fundamental distinction in the schema between definitions that actually appear in HED data (tags, units, unit modifiers) and "meta-definitions", or those that describe other definitions in the schema (schema attributes, unit classes, value classes, and properties). The latter types should be case-insensitive.

**Comment by IanCa** [comment]
Ah yeah, right now modifiers are still case sensitive(even if not symbols)

But when combined with units(that aren't a symbol), they accept either.  I'll plan to do another pass once we pin down our plans, I was just rushing to solve the Volt vs volt problem since it had come up directly.

**Comment by IanCa** [comment]
Is there any reason to still not approve this?

It only adds the Volt == volt test.(eg case not mattering for non symbols)

**Pull request merged**
