### PR TITLE
add codespell: config, workflow and have typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
workflow would only detect when a new typo is introduced, it will not automagically inject its fix somehow.

more info on codespell: https://github.com/codespell-project/codespell

I have excluded `deprecated/`

### CODE REVIEW

**Comment by VisLab** [comment]
okay let's give it a try.

**Comment by VisLab** [comment]
@yarikoptic It didn't give any spelling errors when I merged as far as I can tell.  I suspect that there actually are a few... did I miss something?

**Comment by VisLab** [comment]
@yarikoptic - okay I think I have blundered through reverting --- would you be willing to update and resubmit? 

Here are the things that should be excluded.  tests/, data/,  datasets/, _build

                                                       all .xml files   (These are always generated)
                                                      all .mediawiki files except those that are in a prerelease/ directory  (This one isn't obvious to me as to how to do)

Thx!

**Comment by yarikoptic** [comment]
ok, I will try to get to it !

**Pull request merged**
